### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by Cooper-Kunz** [hashgraph/hedera-proof-of-action-api#2]
Currently the readme just outlines how to setup (which is great) but it doesn't help users understand what the proof of action API is, what they're setting up, or when to use it. Can we update the description with some architecture diagrams, or other helpful materials?

**Comment by mehcode** [comment]
@atul-hedera would probably be the most in-tune here. I have a firm enough grasp to build the thing but I wouldn't trust myself to write up a blurb on why the thing.

**Comment by bmgentile** [comment]
Hey @mehcode and @Cooper-Kunz I'll come up with a description here and use slides/diagrams created by Atul to help. Will publish in a Google Doc here that can be used wherever needed.

**Comment by mehcode** [comment]
Thanks for the assist.
